# Generated by Django 3.1.6 on 2021-02-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=20)),
                ('longitud', models.CharField(blank=True, max_length=20)),
                ('latitud', models.CharField(blank=True, max_length=20)),
                ('estado_geo', models.BooleanField(blank=True)),
            ],
        ),
    ]
